# Generated by Django 3.2.2 on 2021-05-13 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whiteboard_app', '0003_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
