# Generated by Django 3.2.2 on 2021-05-13 10:12

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('whiteboard_app', '0004_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='url',
            field=embed_video.fields.EmbedVideoField(null=True),
        ),
    ]
